### ISSUE TITLE
contribution

### ISSUE THREAD

**Issue by VillainsRule** [GDBOI101/SS-GS#3]
i'm very interested in continuing the legacy of this concept with you & finishing it for a current shell shockers version. personally, i'm unable to figure out how to integrate the game code as i can't see a start game concept. i made [crackedshell](https://github.com/xynacore/CrackedShell) as a concept for SS modding, as well as added a server concept. i've finished a copy of the matchmaker and services to fill in, but i'm interested in figuring out how to fully implement the game websocket.

if you're still interested in developing this, shoot me a discord friend request @ **not1ust** and we can chat. thanks :)

**Comment by GDBOI101** [comment]
Hi! I think that would be awesome! It says you aren't accepting friend requests but feel free to shoot me one I'd be glad to talk! @the1andonly_tjc
